# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: fix-encoding-pragma

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

# There seems to be an issue with black in precommit config for some reason
# -   repo: https://github.com/psf/black
#     rev: 22.12.0
#     hooks:
#     -   id: black

-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.0
    hooks:
    -   id: pylint
