[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "FlowRunner"
authors = [
    {name = "Prithvijit Guha", email = "prithvijit_guha2@hotmail.com"},
]
description = "FlowRunner is a lightweight package to organize and represent Data Engineering/Science workflows"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: Tardis-flow",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
    'click<=8.1.3',
    'Jinja2<=3.1.2'
]
dynamic = ["version"]

[project.optional-dependencies]
pdf = ["ReportLab>=1.2", "RXP"]
rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]

