[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "FlowRunner"
authors = [
    {name = "Prithvijit Guha", email = "prithvijit_guha2@hotmail.com"},
]
description = "FlowRunner is a lightweight package to organize and represent Data Engineering/Science workflows"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: FlowRunner",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"',
    'click<=8.1.3',
    'Jinja2<=3.1.2',
    'coloredlogs>=15.0.1'
]


dynamic = ["version"]


[project.optional-dependencies]
doc = [
    "Sphinx>=6.1.3"
]

dev = [
    "pylint>=2.16.4",
    "black>=23.1.0",
    "pytest>=7.2.1"
]
test = [
    "pytest>=7.2.1"
]


[options]
package_dir=[
    "flowrunner"
]

[options.packages.find]
where=[
    "flowrunner"
]


[project.scripts]
cli = "flowrunner.cli:cli"

[tool.pytest.ini_options]
pythonpath = "flowrunner"
testpaths = [
    "tests"
]
addopts = [
    "-v"
]
