[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "FlowRunner"
authors = [
    {name = "Prithvijit Guha", email = "prithvijit_guha2@hotmail.com"},
]
description = "FlowRunner is a lightweight package to organize and represent Data Engineering/Science workflows"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["one", "two"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: FlowRunner",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    'requests',
    'importlib-metadata; python_version<="3.9"',
    'click>=8.1.3',
    'Jinja2>=3.1.2',
    'coloredlogs>=15.0.1'
]


dynamic = ["version"]


[project.optional-dependencies]
doc = [
    "Sphinx>=6.1.3",
    "pre-commit>=3.1.1"
]

dev = [
    "pylint>=2.16.4",
    "black>=23.1.0",
    "pytest>=7.2.1",
    "pre-commit==3.1.1",
]
test = [
    "pytest>=7.2.1",
    "pre-commit>=3.1.1"
]


[options]
package_dir=[
    "flowrunner"
]

[options.packages.find]
where=[
    "flowrunner"
]


[project.scripts]
cli = "flowrunner.cli:cli"

[tool.pytest.ini_options]
pythonpath = [
    "flowrunner",
    "tests"
    ]
testpaths = [
    "tests"
]
addopts = [
    "--continue-on-collection-errors",
    "-v"
]
