name: "Release to PyPI"

on: workflow_dispatch # has to be triggered manually only

jobs:
  build:
    name: Release
    steps:
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
